"""Emit a standalone ADK 2.x `agent.py` from a GraphSpec — graph or dynamic mode.

The graph emitter walks the same IR the runtime uses, so what you export is
exactly what ran in the Studio (minus the mock engine).
"""

from __future__ import annotations

from .compiler import IR, _wf_name, group_edges, instruction_for, lower
from .spec import AgentNode, GraphSpec, Layer

HELPERS = '''
APPROVE_WORDS = ("approve", "approved", "yes", "y", "ok", "ship", "lgtm")


def text_of(value):
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    parts = getattr(value, "parts", None)
    if parts:
        return "".join(p.text or "" for p in parts if getattr(p, "text", None))
    if isinstance(value, (dict, list)):
        return json.dumps(value, default=str, indent=1)
    return str(value)


def pick_route(text, labels):
    low = text.lower()
    hits = [(low.find(label.lower()), label) for label in labels if label.lower() in low]
    return min(hits)[1] if hits else labels[0]


def is_approved(response):
    if isinstance(response, dict):
        response = response.get("result", response.get("decision", ""))
    return text_of(response).strip().lower().split(" ")[0] in APPROVE_WORDS


def critic_passed(text):
    return text.strip().upper().startswith("PASS")


def first_of(*values):
    return next((v for v in values if v is not None), None)
'''


def _lit(s: str) -> str:
    if "\n" in s and '"""' not in s and "\\" not in s:
        return '"""' + s + '"""'
    return repr(s)


def _header(spec: GraphSpec, mode: str) -> str:
    uses_human = any(n.kind == "human" for layer in spec.layers for n in layer.nodes)
    uses_search = any("google_search" in n.tools for layer in spec.layers for n in layer.nodes)
    lines = [
        f'"""{spec.name} — generated by Stratum ({mode} mode).',
        "",
        spec.description or "Layered agent graph.",
        "Requires google-adk >= 2.0. Put this file in an agent folder and run `adk web`.",
        '"""',
        "",
        "import asyncio" if mode == "dynamic" else "",
        "import json",
        "",
        "from google.adk import Agent, Context, Event, Workflow",
    ]
    if uses_human:
        lines.append("from google.adk.events import RequestInput")
    if uses_search:
        lines.append("from google.adk.tools import google_search")
    lines.append("from google.adk.workflow import JoinNode, node" if mode == "graph"
                 else "from google.adk.workflow import node")
    lines += ["", f"MODEL = {spec.model!r}"]
    return "\n".join(line for i, line in enumerate(lines) if line or i in (5, 8, len(lines) - 2)) + "\n" + HELPERS


def _layer_banner(i: int, layer: Layer) -> str:
    shape = {"stage": "parallel fan-out" if len(layer.nodes) > 1 else "step",
             "router": "exclusive routing", "loop": f"loop ≤{layer.max_iterations}",
             "gate": "human-in-the-loop"}[layer.kind]
    return f"\n\n# ── Layer {i + 1} · {layer.title} ({shape}) " + "─" * max(4, 50 - len(layer.title))


def _agent_src(n: AgentNode, layer: Layer) -> str:
    lines = [f"{n.name} = Agent(", f'    name="{n.name}",',
             f"    model={n.model!r}," if n.model else "    model=MODEL,",
             '    mode="single_turn",', f'    output_key="{n.name}",',
             f"    instruction={_lit(instruction_for(n, layer))},"]
    if "google_search" in n.tools:
        lines.append("    tools=[google_search],")
    return "\n".join(lines + [")"])


def _code_src(n: AgentNode) -> str:
    if n.op == "passthrough":
        body = f'    return Event(output=node_input, state={{"{n.name}": text_of(node_input)}})'
    else:
        body = ('    out = ("\\n\\n".join(f"## {k}\\n{text_of(v)}" for k, v in node_input.items())\n'
                "           if isinstance(node_input, dict) else text_of(node_input))\n"
                f'    return Event(output=out, state={{"{n.name}": out}})')
    return (f"def {n.name}(node_input):\n"
            f'    """Deterministic {n.op} — a FunctionNode: no model call, zero token cost."""\n{body}')


def _human_src(n: AgentNode) -> str:
    return (f'@node(name="{n.name}", rerun_on_resume=False)\n'
            f"async def {n.name}(ctx: Context, node_input):\n"
            f'    """Pauses the workflow (RequestInput) until a human answers."""\n'
            f'    ctx.state["_gate_{n.name}"] = text_of(node_input)\n'
            f"    yield RequestInput(message={(n.instruction or 'Approve to continue?')!r},\n"
            f'                       payload={{"preview": text_of(node_input)[:1500]}})')


def _source_for(n: AgentNode, layer: Layer) -> str:
    if n.kind == "code":
        return _code_src(n)
    if n.kind == "human":
        return _human_src(n)
    return _agent_src(n, layer)


# ─────────────────────────────── graph mode ───────────────────────────────

def graph(spec: GraphSpec, ir: IR | None = None) -> str:
    ir = ir or lower(spec)
    out = [_header(spec, "graph")]
    layer_of_target = {n.name: n.layer for n in ir.nodes.values() if n.layer is not None}

    for i, layer in enumerate(spec.layers):
        out.append(_layer_banner(i, layer))
        for n in layer.nodes:
            join = ir.nodes.get(f"join_{n.name}")
            if join is not None and layer_of_target.get(n.name) is layer:
                out.append(f'\n{join.name} = JoinNode(name="{join.name}")  # waits for every upstream branch')
            out.append("\n" + _source_for(n, layer))
        for ir_node in ir.nodes.values():
            if ir_node.layer is layer and ir_node.internal and ir_node.role != "join":
                out.append("\n" + _internal_src(ir_node.name, ir_node.role, ir_node.extra, ir_node.spec))

    plain, routed = group_edges(ir)

    def ref(name: str) -> str:
        return '"START"' if name == "START" else name

    def many(names: list[str]) -> str:
        return ref(names[0]) if len(names) == 1 else "(" + ", ".join(names) + ")"

    rows = [f"        ({ref(src)}, {many(dsts)})," for src, dsts in plain.items()]
    rows += ["        (" + ref(src) + ", {" + ", ".join(f'"{lbl}": {many(d)}' for lbl, d in m.items()) + "}),"
             for src, m in routed.items()]
    out.append("\n\n# ── Graph ────────────────────────────────────────────────────")
    out.append(f'\nroot_agent = Workflow(\n    name="{_wf_name(spec)}",\n    edges=[\n' + "\n".join(rows) + "\n    ],\n)\n")
    return "\n".join(out)


def _internal_src(name: str, role: str, x: dict, spec_node: AgentNode | None) -> str:
    if role == "router_fn":
        keys = x["context"]
        ctx_expr = (f'ctx.state.get("{keys[0]}")' if len(keys) == 1
                    else "{" + ", ".join(f'"{k}": ctx.state.get("{k}")' for k in keys) + "}")
        return (f"def {name}(ctx: Context, node_input):\n"
                f'    """Maps the classifier reply to a route label; branches get the router\'s input."""\n'
                f"    label = pick_route(text_of(node_input), {x['labels']!r})\n"
                f"    return Event(output={ctx_expr}, route=label)")
    if role == "loop_gate":
        g, key = x["generator"], f"_iter_{name}"
        return (f"def {name}(ctx: Context, node_input):\n"
                f'    """Loop controller: back-edge to {g} until the critic says PASS (max {x["max"]})."""\n'
                f'    it = int(ctx.state.get("{key}", 0)) + 1\n'
                f'    draft = ctx.state.get("{g}")\n'
                f'    if critic_passed(text_of(node_input)) or it >= {x["max"]}:\n'
                f'        return Event(output=draft, route="done", state={{"{key}": 0}})\n'
                f'    return Event(output={{"draft": draft, "feedback": text_of(node_input)}},\n'
                f'                 route="revise", state={{"{key}": it}})')
    if role == "human_decide":
        ask = x["ask"]
        return (f"def {name}(ctx: Context, node_input):\n"
                f"    if is_approved(node_input):\n"
                f'        return Event(output=ctx.state.get("_gate_{ask}"), route="approved")\n'
                f"    return Event(output=\"Rejected at gate '{ask}'.\", route=\"rejected\",\n"
                f"                 message=\"Run stopped: '{ask}' was rejected.\")")
    raise ValueError(role)


# ─────────────────────────────── dynamic mode ───────────────────────────────

def dynamic(spec: GraphSpec) -> str:
    lower(spec)
    out = [_header(spec, "dynamic")]
    for i, layer in enumerate(spec.layers):
        out.append(_layer_banner(i, layer))
        for n in layer.nodes:
            out.append("\n" + _source_for(n, layer))

    by_id = {n.id: n for layer in spec.layers for n in layer.nodes}
    var: dict[str, str] = {}  # node id -> python variable holding its output
    maybe_none: dict[str, str | None] = {}  # var -> router name if it only exists on a branch
    body: list[str] = ['    user_input = ctx.state.get("user_input", text_of(node_input))']
    prev: list[str] = []
    last = "user_input"
    skip_next = False
    router_input = "user_input"

    def input_expr(ids: list[str]) -> str:
        vs = [var[i] for i in ids]
        if not vs:
            return "user_input"
        if len(vs) == 1:
            return vs[0]
        routers = {maybe_none.get(v) for v in vs}
        if None not in routers and len(routers) == 1:
            return "first_of(" + ", ".join(vs) + ")"
        return "{" + ", ".join(f'"{by_id[i].name}": {var[i]}' for i in ids) + "}"

    for li, layer in enumerate(spec.layers):
        body.append(f"\n    # Layer {li + 1} · {layer.title}")
        if layer.kind == "stage":
            if skip_next:
                skip_next = False
                continue
            free, guarded = [], []
            for n in layer.nodes:
                deps = prev if n.depends_on is None else n.depends_on
                dvars = [var[d] for d in deps]
                inp = input_expr(deps)
                branch = next((maybe_none[v] for v in dvars if maybe_none.get(v)), None)
                exclusive_merge = inp.startswith("first_of(")
                var[n.id] = f"{n.name}_out"
                if branch and not exclusive_merge:
                    guarded.append((n, inp, dvars))
                    maybe_none[var[n.id]] = branch
                else:
                    free.append((n, inp))
            if len(free) > 1:
                body.append("    " + ", ".join(var[n.id] for n, _ in free) + " = await asyncio.gather(")
                body += [f"        ctx.run_node({n.name}, {inp})," for n, inp in free]
                body.append("    )")
            elif free:
                n, inp = free[0]
                body.append(f"    {var[n.id]} = await ctx.run_node({n.name}, {inp})")
            for n, inp, dvars in guarded:
                cond = " and ".join(f"{v} is not None" for v in dvars)
                body.append(f"    {var[n.id]} = await ctx.run_node({n.name}, {inp}) if {cond} else None")
            prev = [n.id for n in layer.nodes]
            last = input_expr(prev)

        elif layer.kind == "router":
            n = layer.nodes[0]
            deps = prev if n.depends_on is None else n.depends_on
            router_input = input_expr(deps)
            var[n.id] = f"{n.name}_out"
            body.append(f"    {var[n.id]} = await ctx.run_node({n.name}, {router_input})")
            labels = [r.label for r in n.routes]
            body.append(f"    route = pick_route(text_of({var[n.id]}), {labels!r})")
            targets = [by_id[r.target] for r in n.routes]
            for t in targets:
                var[t.id] = f"{t.name}_out"
                maybe_none[var[t.id]] = n.name
            body.append("    " + " = ".join(var[t.id] for t in targets) + " = None")
            for j, r in enumerate(n.routes):
                kw = "if" if j == 0 else "elif"
                t = by_id[r.target]
                body.append(f'    {kw} route == "{r.label}":')
                body.append(f"        {var[t.id]} = await ctx.run_node({t.name}, {router_input})")
            prev = [t.id for t in targets]
            last = input_expr(prev)
            skip_next = True

        elif layer.kind == "loop":
            gen, critic = layer.nodes
            deps = prev if gen.depends_on is None else gen.depends_on
            g = f"{gen.name}_out"
            body += [f"    payload = {input_expr(deps)}", f"    {g} = None",
                     f"    for _ in range({layer.max_iterations}):",
                     f"        {g} = await ctx.run_node({gen.name}, payload)",
                     f"        verdict = await ctx.run_node({critic.name}, {g})",
                     "        if critic_passed(text_of(verdict)):",
                     "            break",
                     f'        payload = {{"draft": {g}, "feedback": verdict}}']
            var[gen.id] = var[critic.id] = g
            prev, last = [gen.id], g

        elif layer.kind == "gate":
            h = layer.nodes[0]
            deps = prev if h.depends_on is None else h.depends_on
            up = input_expr(deps)
            body += [f"    decision = await ctx.run_node({h.name}, {up})",
                     "    if not is_approved(decision):",
                     f"        return Event(output=\"Rejected at gate '{h.name}'.\",",
                     f"                     message=\"Run stopped: '{h.name}' was rejected.\")",
                     f"    {h.name}_out = {up}"]
            var[h.id] = f"{h.name}_out"
            prev, last = [h.id], var[h.id]

    body.append(f"\n    return {last}")
    out.append("\n\n# ── Dynamic orchestrator ────────────────────────────────────")
    out.append('\n@node(name="orchestrator", rerun_on_resume=True)\n'
               "async def orchestrator(ctx: Context, node_input):\n"
               '    """Plain Python control flow over ctx.run_node — ADK checkpoints every call,\n'
               '    so a human gate can pause and resume without re-running finished agents."""\n'
               + "\n".join(body))
    out.append(f'\n\nroot_agent = Workflow(name="{_wf_name(spec)}", edges=[("START", orchestrator)])\n')
    return "\n".join(out)
